### ISSUE TITLE
How I can get price in callback response ominay paratika

### ISSUE THREAD

**Issue by sumiodz** [yasinkuyu/omnipay-paratika#3]
Hi You have function getTransactionId() can we create function return with amount ???Please reply asap

**Comment by yasinkuyu** [comment]
Of course this is possible.

    if ($response->isSuccessful()) {
    
            $data = $response->getQueryDetails()

            echo data["amount"]
            echo data["currency"]
            // etc..

    } else { ... }


Sample response 

ÖRNEK CEVAP
					
{
  "action" : "SALE",
  "merchant" : "10000000",
  "amount" : 18.75,
  "currency" : "TRY",
  "apiMerchantId" : "600600000",
  "paymentSystem" : "My Finans Webpos Online Account (Test)",
  "paymentSystemType" : "FINANS",
  "paymentSystemEftCode" : "0111",
  "pgTranDate" : "20160729 12:18:53",
  "merchantPaymentId" : "PaymentId-3gMvdMzXMj2q",
  "pgTranId" : "16211MS3D00124776",
  "pgTranRefId" : "621112352883",
  "pgOrderId" : "PaymentId-3gMvdMzXMj2q",
  "responseCode" : "00",
  "responseMsg" : "Approved",
  "tmxSessionQueryOutput" : ""
}

**Comment by sumiodz** [comment]
But I am using

 $options = [
                            'amount'        => $cart_total_amount,
                            'currency'      => 'TRY',
                            //'installment'   => 0, // Taksit
                            'orderId'       => $unique_conversation_id, //
Benzersiz olmalı.
                            'returnUrl'     => $callback_url,
                            'cancelUrl'     => $callback_url,
                            'sessionType'   => 'PAYMENTSESSION', //Diğer
parametreler: PAYMENTSESSION WALLETSESSION
                            'card'          => $card,

                  ];

payment seesion not query installement this will used in

 $data = $response->getQueryDetails()

query installemnet

**Comment by yasinkuyu** [comment]
If you are trying to make an installment, remove the comment line.

    //'installment'   => 0, // Taksit
    to
    'installment'   => 0, // Taksit

**Comment by sumiodz** [comment]
I have implement this payment gateway ist was working fine now I am again
tetsing it will show


  [data:protected] => Array        (            [errorCode] =>
ERR10108            [responseCode] => 99            [errorMsg] => Üye
iş yeri onaylanmamış            [responseMsg] => Declined
[violatorParam] => MERCHANT        )


You have idea about this?

**Comment by yasinkuyu** [comment]
[errorMsg] => Üye iş yeri onaylanmamış >>>> Membership is not approved.

$gateway = Omnipay::create('Paratika');
$gateway->setMerchant('YOUR MERCHANT ID');
$gateway->setMerchantUser('YOUR USERNAME');
$gateway->setMerchantPassword('YOUR PASSWORD');
$gateway->setSecretKey('YOR SECRET KEY');
$gateway->setBank('ISBANK');

**Comment by sumiodz** [comment]
I already put the infomation and it was working but now its showing this
Membership is not approved.Is that error from  paratika admin?? need to
contact to supoport??

**Comment by yasinkuyu** [comment]
Yes, contact Paratika support.

**Comment by sumiodz** [comment]
Morning


can you tell me should we pass items


ORDERITEMS:  [
        {
            "code": "T00D3AITCC",
            "name": "Galaxy Note 3",
            "description": "Description of Galaxy Note 3",
            "quantity": 2,
            "amount": 449.99
        },
        {
            "code": "B00D9AVYBM",
            "name": "Samsung Galaxy S III",
            "description": "Samsung Galaxy S III (S3) Triband White
(Boost Mobile)",
            "quantity": 1,
            "amount": 149.95
        },
        {
            "code": "B00NQGP5M8",
            "name": "Apple iPhone 6",
            "description": "Apple iPhone 6, Gold, 64 GB (Unlocked) by Apple",
            "quantity": 1,
            "amount": 139.95
        },
        {
            "code": "B00U8KSUIG",
            "name": "Samsung Galaxy S6",
            "description": "Samsung Galaxy S6 SM-G920F 32GB (FACTORY
UNLOCKED) 5.1 QHDBlack-InternationalVersion",
            "quantity": 1,
            "amount": 129.95
        }
]

  in payment session and I need these items in return when payment
succesffull and come to callback function is that possible ???????


Please help me its very urgent

**Comment by yasinkuyu** [comment]
Not yet possible.
Check this; https://github.com/yasinkuyu/omnipay-paratika/blob/a284330ef603aeb3d51e6a64e4a66cce4f3097a5/src/Message/AbstractPayment.php#L124

**Comment by sumiodz** [comment]
yes I already checked this can you tell me how  can I set in options
$item=array(
'code' => 'Test001',
'name' => 'Ürün adı',
'description' => 'Açıklama',
'quantity' => 1,
'amount' => $this->getAmount()
);

$options = [
                            'amount'        => $paypoints,
                            'currency'      => 'TRY',
                            //'installment'   => 0, // Taksit
                            'orderId'       => $unique_conversation_id, //
Benzersiz olmalı.
                            'returnUrl'     => $callback_url,
                            'cancelUrl'     => $callback_url,
                            'sessionType'   => 'PAYMENTSESSION', //Diğer
parametreler: PAYMENTSESSION WALLETSESSION
                            'card'          => $card,
                            'items'       =>$item


                  ];


I am doing like this but its not working can you tell me how I can proceed
with this I will do code my self


Thanks for reply

**Comment by yasinkuyu** [comment]
Currently, this is not possible.
It will be done in the next version.
